version: "3"
services:
  app:
    build:
      context: ./source_code
    container_name: app-laravel
    ports:
      - "9000:9000"
    volumes:
      - ./source_code/:/var/www/html/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: app-nginx
    volumes:
      - ./source_code/:/var/www/html/
      - ./docker/nginx/vhost.template:/etc/nginx/conf.d/vhost.template
    ports:
      - "80:80"
    environment:
      - NGINX_SERVER_NAME=localhost
    command: /bin/bash -c "envsubst '$$NGINX_SERVER_NAME' < /etc/nginx/conf.d/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - app-network
  mysql:
    image: mysql:latest
    container_name: app-db
    ports:
      - "3306:3306"
    depends_on:
      - app
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: app-pma
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysqldata:
