version: "3"
services:
  app:
    build:
      context: ./source_code
    hostname: app
    ports:
      - "9000:9000"
    volumes:
      - ./source_code/:/var/www/html/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./source_code/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    depends_on:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
